site: alexanderulmer.com
url: https://www.alexanderulmer.com
title: alexanderulmer
description: Thoughts in no particular order
author:
  twitter: alexanderjulmer
  name: Alexander Ulmer
  email: alexanderjulmer@gmail.com
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache

sass:
  style: compact

plugins:
  - jekyll-paginate
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /posts/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
